# frozen_string_literal: true

source "https://rubygems.org"

ruby "3.2.7"

gem "sinatra", "~> 4.0.0"
gem "puma", "~> 6.4.3"
gem "rack", "~> 3.1.8"
gem "rack-session", "~> 2.0.0"
gem "rexml", "~> 3.3.9"
gem "rackup"

group :development do
  gem "standard"
end
